import { Permission, RoleDefinition } from './permission.model';

/** Everything an authenticated person can do to their own account. */
const SELF: Permission[] = ['profile.view', 'profile.edit', 'notifications.view'];

/** Read-only across the operational modules — the Auditor's baseline. */
const READ_ALL: Permission[] = [
  'employees.view',
  'departments.view',
  'projects.view',
  'requests.view',
  'workflows.view',
  'assets.view',
  'documents.view',
  'analytics.view',
  'reports.view',
];

export const ROLES: RoleDefinition[] = [
  {
    id: 'super-admin',
    name: 'Super Admin',
    description: 'Platform administrator. Everything, including roles and integrations.',
    scope: 'Organisation',
    permissions: [
      ...READ_ALL,
      ...SELF,
      'employees.create',
      'employees.edit',
      'employees.delete',
      'departments.create',
      'departments.edit',
      'projects.create',
      'projects.edit',
      'projects.archive',
      'projects.manage_members',
      'requests.create',
      'requests.approve',
      'requests.reject',
      'workflows.create',
      'workflows.edit',
      'workflows.publish',
      'assets.create',
      'assets.edit',
      'assets.assign',
      'documents.upload',
      'documents.edit',
      'documents.share',
      'reports.create',
      'reports.export',
      'settings.view',
      'settings.edit',
      'roles.view',
      'roles.manage',
      'audit.view',
      'audit.export',
    ],
  },
  {
    id: 'org-admin',
    name: 'Organization Admin',
    description: 'Runs the organisation. No platform-level role management.',
    scope: 'Organisation',
    permissions: [
      ...READ_ALL,
      ...SELF,
      'employees.create',
      'employees.edit',
      'employees.delete',
      'departments.create',
      'departments.edit',
      'projects.create',
      'projects.edit',
      'projects.archive',
      'projects.manage_members',
      'requests.create',
      'requests.approve',
      'requests.reject',
      'workflows.create',
      'workflows.edit',
      'workflows.publish',
      'assets.create',
      'assets.edit',
      'assets.assign',
      'documents.upload',
      'documents.edit',
      'documents.share',
      'reports.create',
      'reports.export',
      'settings.view',
      'settings.edit',
      'roles.view',
      'audit.view',
      'audit.export',
    ],
  },
  {
    id: 'hr-manager',
    name: 'HR Manager',
    description: 'Workforce and employee operations. No projects, assets or audit.',
    scope: 'Organisation',
    permissions: [
      ...SELF,
      'employees.view',
      'employees.create',
      'employees.edit',
      'departments.view',
      'departments.edit',
      'requests.view',
      'requests.create',
      'requests.approve',
      'requests.reject',
      'workflows.view',
      'documents.view',
      'documents.upload',
      'documents.edit',
      'analytics.view',
      'reports.view',
      'reports.export',
      'settings.view',
    ],
  },
  {
    id: 'finance-manager',
    name: 'Finance Manager',
    description: 'Budgets and finance approvals. Reads projects and departments.',
    scope: 'Organisation',
    permissions: [
      ...SELF,
      'employees.view',
      'departments.view',
      'projects.view',
      'assets.view',
      'requests.view',
      'requests.create',
      'requests.approve',
      'requests.reject',
      'workflows.view',
      'documents.view',
      'documents.upload',
      'analytics.view',
      'reports.view',
      'reports.export',
      'settings.view',
    ],
  },
  {
    id: 'dept-manager',
    name: 'Department Manager',
    description: 'Their department and team. Approves team requests.',
    scope: 'Department',
    permissions: [
      ...SELF,
      'employees.view',
      'departments.view',
      'projects.view',
      'projects.edit',
      'requests.view',
      'requests.create',
      'requests.approve',
      'requests.reject',
      'assets.view',
      'documents.view',
      'documents.upload',
      'analytics.view',
      'reports.view',
    ],
  },
  {
    id: 'project-manager',
    name: 'Project Manager',
    description: 'Project delivery — members, milestones and project requests.',
    scope: 'Project',
    permissions: [
      ...SELF,
      'employees.view',
      'projects.view',
      'projects.create',
      'projects.edit',
      'projects.archive',
      'projects.manage_members',
      'requests.view',
      'requests.create',
      'requests.approve',
      'assets.view',
      'documents.view',
      'documents.upload',
      'documents.edit',
      'workflows.view',
      'analytics.view',
      'reports.view',
    ],
  },
  {
    id: 'employee',
    name: 'Employee',
    description: 'Day-to-day user. Own requests, projects, assets and documents.',
    scope: 'Own records',
    permissions: [
      ...SELF,
      'projects.view',
      'requests.view',
      'requests.create',
      'assets.view',
      'documents.view',
      'reports.view',
    ],
  },
  {
    id: 'auditor',
    name: 'Auditor',
    description: 'Read-only across the platform, plus the audit trail.',
    scope: 'Read-only',
    permissions: [...READ_ALL, ...SELF, 'audit.view', 'audit.export', 'reports.export'],
  },
];

export const DEFAULT_ROLE: RoleDefinition['id'] = 'org-admin';
